package com.github.andreyasadchy.xtra.ui.chat

import com.github.andreyasadchy.xtra.R
import java.util.Locale

/** The groups shown inside the emoji picker. */
enum class EmojiPickerCategory(val titleRes: Int) {
    ALL(R.string.emoji_category_all),
    SMILEYS(R.string.emoji_category_smileys),
    PEOPLE(R.string.emoji_category_people),
    ANIMALS(R.string.emoji_category_animals),
    FOOD(R.string.emoji_category_food),
    TRAVEL(R.string.emoji_category_travel),
    ACTIVITIES(R.string.emoji_category_activities),
    OBJECTS(R.string.emoji_category_objects),
    SYMBOLS(R.string.emoji_category_symbols),
    FLAGS(R.string.emoji_category_flags),
}

/** A local Unicode emoji that can be addressed by the same colon syntax used by chat emotes. */
data class EmojiPickerItem(
    val name: String,
    val value: String,
    val category: EmojiPickerCategory = EmojiPickerCategory.SMILEYS,
    val aliases: List<String> = listOf(name),
    val matchedAlias: String? = null,
) {
    val alias: String get() = ":${matchedAlias ?: name}:"

    override fun toString(): String = alias
}

data class EmojiAliasMatch(
    val item: EmojiPickerItem,
    val matchedAlias: String,
    val start: Int,
    val end: Int,
)

data class EmojiAliasPrefix(
    val text: String,
    val start: Int,
    val end: Int,
)

internal object EmojiPickerCatalog {
    val categories: List<EmojiPickerCategory> = EmojiPickerCategory.entries

    val items: List<EmojiPickerItem> by lazy {
        smileys + people + animals + food + travel + activities + objects + symbols + flags
    }

    private val itemsByCategory by lazy { items.groupBy(EmojiPickerItem::category) }
    private val byAlias by lazy {
        buildMap {
            items.flatMap { item -> item.aliases.map { alias -> ":${alias.lowercase(Locale.ROOT)}:" to item } }
                .forEach { (alias, item) ->
                    val previous = put(alias, item)
                    check(previous == null || previous == item) { "Duplicate emoji alias: $alias" }
                }
        }
    }

    fun itemsFor(category: EmojiPickerCategory): List<EmojiPickerItem> =
        if (category == EmojiPickerCategory.ALL) items else itemsByCategory[category].orEmpty()

    fun findByAlias(alias: String): EmojiPickerItem? = byAlias[alias.lowercase(Locale.ROOT)]

    fun findAliasMatches(text: CharSequence): List<EmojiAliasMatch> = buildList {
        val value = text.toString()
        rawAliasMatches(value).forEach { match ->
            if (isEscaped(value, match.range.first) || isInsideUrl(value, match.range.first, match.range.last + 1)) {
                return@forEach
            }
            byAlias[match.value.lowercase(Locale.ROOT)]?.let { item ->
                add(
                    EmojiAliasMatch(
                        item = item,
                        matchedAlias = match.value,
                        start = match.range.first,
                        end = match.range.last + 1,
                    ),
                )
            }
        }
    }

    fun replaceAliases(text: CharSequence): String {
        val value = text.toString()
        val matches = rawAliasMatches(value).toList()
        if (matches.isEmpty()) return value
        return buildString(value.length) {
            var cursor = 0
            matches.forEach { match ->
                val start = match.range.first
                val end = match.range.last + 1
                if (isEscaped(value, start)) {
                    append(value, cursor, start - 1)
                    append(value, start, end)
                } else if (isInsideUrl(value, start, end)) {
                    append(value, cursor, end)
                } else {
                    byAlias[match.value.lowercase(Locale.ROOT)]?.let { item ->
                        append(value, cursor, start)
                        append(item.value)
                    } ?: append(value, cursor, end)
                }
                cursor = end
            }
            append(value, cursor, value.length)
        }
    }

    fun findAliasPrefixAtCursor(text: CharSequence, cursor: Int): EmojiAliasPrefix? {
        val value = text.toString()
        if (value.isEmpty()) return null
        val position = cursor.coerceIn(0, value.length)
        var scanEnd = position
        if (scanEnd > 0 && value[scanEnd - 1].isWhitespace()) return null
        if (scanEnd > 0 && !isAliasNameChar(value[scanEnd - 1]) && value[scanEnd - 1] != ':') {
            scanEnd--
        }
        val searchEnd = if (
            scanEnd > 1 && value[scanEnd - 1] == ':' && isAliasNameChar(value[scanEnd - 2])
        ) {
            scanEnd - 2
        } else {
            scanEnd - 1
        }
        val colon = value.lastIndexOf(':', searchEnd.coerceAtLeast(0))
        if (colon < 0 || colon >= scanEnd || (colon > 0 && isAliasBoundaryChar(value[colon - 1])) || isEscaped(value, colon)) {
            return null
        }
        var end = colon + 1
        while (end < value.length && isAliasNameChar(value[end])) end++
        if (end == colon + 1) return null
        if (end < value.length && value[end] == ':') end++
        if (end != scanEnd || isInsideUrl(value, colon, end)) return null
        return EmojiAliasPrefix(value.substring(colon, end), colon, end)
    }

    private fun smiley(name: String, value: String, vararg aliases: String) = emoji(EmojiPickerCategory.SMILEYS, name, value, *aliases)
    private fun person(name: String, value: String, vararg aliases: String) = emoji(EmojiPickerCategory.PEOPLE, name, value, *aliases)
    private fun animal(name: String, value: String, vararg aliases: String) = emoji(EmojiPickerCategory.ANIMALS, name, value, *aliases)
    private fun foodItem(name: String, value: String, vararg aliases: String) = emoji(EmojiPickerCategory.FOOD, name, value, *aliases)
    private fun travelItem(name: String, value: String, vararg aliases: String) = emoji(EmojiPickerCategory.TRAVEL, name, value, *aliases)
    private fun activity(name: String, value: String, vararg aliases: String) = emoji(EmojiPickerCategory.ACTIVITIES, name, value, *aliases)
    private fun objectItem(name: String, value: String, vararg aliases: String) = emoji(EmojiPickerCategory.OBJECTS, name, value, *aliases)
    private fun symbol(name: String, value: String, vararg aliases: String) = emoji(EmojiPickerCategory.SYMBOLS, name, value, *aliases)
    private fun flag(name: String, value: String, vararg aliases: String) = emoji(EmojiPickerCategory.FLAGS, name, value, *aliases)

    private fun emoji(
        category: EmojiPickerCategory,
        name: String,
        value: String,
        vararg aliases: String,
    ) = EmojiPickerItem(name, value, category, listOf(name) + aliases.toList())

    private val smileys: List<EmojiPickerItem> = listOf(
        smiley("grinning", "😀"),
        smiley("smiley", "😃"),
        smiley("smile", "😄"),
        smiley("grin", "😁"),
        smiley("laughing", "😆", "satisfied"),
        smiley("sweat_smile", "😅"),
        smiley("rofl", "🤣"),
        smiley("joy", "😂"),
        smiley("slightly_smiling_face", "🙂"),
        smiley("upside_down_face", "🙃"),
        smiley("melting_face", "🫠"),
        smiley("wink", "😉"),
        smiley("blush", "😊"),
        smiley("innocent", "😇"),
        smiley("smiling_face_with_three_hearts", "🥰"),
        smiley("heart_eyes", "😍"),
        smiley("star_struck", "🤩"),
        smiley("kissing_heart", "😘"),
        smiley("kissing", "😗"),
        smiley("relaxed", "☺️"),
        smiley("kissing_closed_eyes", "😚"),
        smiley("kissing_smiling_eyes", "😙"),
        smiley("smiling_face_with_tear", "🥲"),
        smiley("yum", "😋"),
        smiley("stuck_out_tongue", "😛"),
        smiley("stuck_out_tongue_winking_eye", "😜"),
        smiley("zany_face", "🤪"),
        smiley("stuck_out_tongue_closed_eyes", "😝"),
        smiley("money_mouth_face", "🤑"),
        smiley("hugs", "🤗"),
        smiley("hand_over_mouth", "🤭"),
        smiley("face_with_open_eyes_and_hand_over_mouth", "🫢"),
        smiley("face_with_peeking_eye", "🫣"),
        smiley("shushing_face", "🤫"),
        smiley("thinking", "🤔"),
        smiley("saluting_face", "🫡"),
        smiley("zipper_mouth_face", "🤐"),
        smiley("raised_eyebrow", "🤨"),
        smiley("neutral_face", "😐"),
        smiley("expressionless", "😑"),
        smiley("no_mouth", "😶"),
        smiley("dotted_line_face", "🫥"),
        smiley("face_in_clouds", "😶‍🌫️"),
        smiley("smirk", "😏"),
        smiley("unamused", "😒"),
        smiley("roll_eyes", "🙄"),
        smiley("grimacing", "😬"),
        smiley("face_exhaling", "😮‍💨"),
        smiley("lying_face", "🤥"),
        smiley("shaking_face", "🫨"),
        smiley("relieved", "😌"),
        smiley("pensive", "😔"),
        smiley("sleepy", "😪"),
        smiley("drooling_face", "🤤"),
        smiley("sleeping", "😴"),
        smiley("mask", "😷"),
        smiley("face_with_thermometer", "🤒"),
        smiley("face_with_head_bandage", "🤕"),
        smiley("nauseated_face", "🤢"),
        smiley("vomiting_face", "🤮"),
        smiley("sneezing_face", "🤧"),
        smiley("hot_face", "🥵"),
        smiley("cold_face", "🥶"),
        smiley("woozy_face", "🥴"),
        smiley("dizzy_face", "😵"),
        smiley("face_with_spiral_eyes", "😵‍💫"),
        smiley("exploding_head", "🤯"),
        smiley("cowboy_hat_face", "🤠"),
        smiley("partying_face", "🥳"),
        smiley("disguised_face", "🥸"),
        smiley("sunglasses", "😎"),
        smiley("nerd_face", "🤓"),
        smiley("monocle_face", "🧐"),
        smiley("confused", "😕"),
        smiley("face_with_diagonal_mouth", "🫤"),
        smiley("worried", "😟"),
        smiley("slightly_frowning_face", "🙁"),
        smiley("frowning_face", "☹️"),
        smiley("open_mouth", "😮"),
        smiley("hushed", "😯"),
        smiley("astonished", "😲"),
        smiley("flushed", "😳"),
        smiley("pleading_face", "🥺"),
        smiley("face_holding_back_tears", "🥹"),
        smiley("frowning", "😦"),
        smiley("anguished", "😧"),
        smiley("fearful", "😨"),
        smiley("cold_sweat", "😰"),
        smiley("disappointed_relieved", "😥"),
        smiley("cry", "😢"),
        smiley("sob", "😭"),
        smiley("scream", "😱"),
        smiley("confounded", "😖"),
        smiley("persevere", "😣"),
        smiley("disappointed", "😞"),
        smiley("sweat", "😓"),
        smiley("weary", "😩"),
        smiley("tired_face", "😫"),
        smiley("yawning_face", "🥱"),
        smiley("triumph", "😤"),
        smiley("rage", "😡", "pout"),
        smiley("angry", "😠"),
        smiley("cursing_face", "🤬"),
        smiley("smiling_imp", "😈"),
        smiley("imp", "👿"),
        smiley("skull", "💀"),
        smiley("skull_and_crossbones", "☠️"),
        smiley("hankey", "💩", "poop", "shit"),
        smiley("clown_face", "🤡"),
        smiley("japanese_ogre", "👹"),
        smiley("japanese_goblin", "👺"),
        smiley("ghost", "👻"),
        smiley("alien", "👽"),
        smiley("space_invader", "👾"),
        smiley("robot", "🤖"),
        smiley("smiley_cat", "😺"),
        smiley("smile_cat", "😸"),
        smiley("joy_cat", "😹"),
        smiley("heart_eyes_cat", "😻"),
        smiley("smirk_cat", "😼"),
        smiley("kissing_cat", "😽"),
        smiley("scream_cat", "🙀"),
        smiley("crying_cat_face", "😿"),
        smiley("pouting_cat", "😾"),
        smiley("see_no_evil", "🙈"),
        smiley("hear_no_evil", "🙉"),
        smiley("speak_no_evil", "🙊"),
        smiley("love_letter", "💌"),
        smiley("cupid", "💘"),
        smiley("gift_heart", "💝"),
        smiley("sparkling_heart", "💖"),
        smiley("heartpulse", "💗"),
        smiley("heartbeat", "💓"),
        smiley("revolving_hearts", "💞"),
        smiley("two_hearts", "💕"),
        smiley("heart_decoration", "💟"),
        smiley("heavy_heart_exclamation", "❣️"),
        smiley("broken_heart", "💔"),
        smiley("heart_on_fire", "❤️‍🔥"),
        smiley("mending_heart", "❤️‍🩹"),
        smiley("heart", "❤️"),
        smiley("pink_heart", "🩷"),
        smiley("orange_heart", "🧡"),
        smiley("yellow_heart", "💛"),
        smiley("green_heart", "💚"),
        smiley("blue_heart", "💙"),
        smiley("light_blue_heart", "🩵"),
        smiley("purple_heart", "💜"),
        smiley("brown_heart", "🤎"),
        smiley("black_heart", "🖤"),
        smiley("grey_heart", "🩶"),
        smiley("white_heart", "🤍"),
        smiley("kiss", "💋"),
        smiley("100", "💯"),
        smiley("anger", "💢"),
        smiley("boom", "💥", "collision"),
        smiley("dizzy", "💫"),
        smiley("sweat_drops", "💦"),
        smiley("dash", "💨"),
        smiley("hole", "🕳️"),
        smiley("speech_balloon", "💬"),
        smiley("eye_speech_bubble", "👁️‍🗨️"),
        smiley("left_speech_bubble", "🗨️"),
        smiley("right_anger_bubble", "🗯️"),
        smiley("thought_balloon", "💭"),
        smiley("zzz", "💤"),
    )

    private val people: List<EmojiPickerItem> = listOf(
        person("wave", "👋"),
        person("raised_back_of_hand", "🤚"),
        person("raised_hand_with_fingers_splayed", "🖐️"),
        person("hand", "✋", "raised_hand"),
        person("vulcan_salute", "🖖"),
        person("rightwards_hand", "🫱"),
        person("leftwards_hand", "🫲"),
        person("palm_down_hand", "🫳"),
        person("palm_up_hand", "🫴"),
        person("leftwards_pushing_hand", "🫷"),
        person("rightwards_pushing_hand", "🫸"),
        person("ok_hand", "👌"),
        person("pinched_fingers", "🤌"),
        person("pinching_hand", "🤏"),
        person("v", "✌️"),
        person("crossed_fingers", "🤞"),
        person("hand_with_index_finger_and_thumb_crossed", "🫰"),
        person("love_you_gesture", "🤟"),
        person("metal", "🤘"),
        person("call_me_hand", "🤙"),
        person("point_left", "👈"),
        person("point_right", "👉"),
        person("point_up_2", "👆"),
        person("middle_finger", "🖕", "fu"),
        person("point_down", "👇"),
        person("point_up", "☝️"),
        person("index_pointing_at_the_viewer", "🫵"),
        person("+1", "👍", "thumbsup"),
        person("-1", "👎", "thumbsdown"),
        person("fist_raised", "✊", "fist"),
        person("fist_oncoming", "👊", "facepunch", "punch"),
        person("fist_left", "🤛"),
        person("fist_right", "🤜"),
        person("clap", "👏"),
        person("raised_hands", "🙌"),
        person("heart_hands", "🫶"),
        person("open_hands", "👐"),
        person("palms_up_together", "🤲"),
        person("handshake", "🤝"),
        person("pray", "🙏"),
        person("writing_hand", "✍️"),
        person("nail_care", "💅"),
        person("selfie", "🤳"),
        person("muscle", "💪"),
        person("mechanical_arm", "🦾"),
        person("mechanical_leg", "🦿"),
        person("leg", "🦵"),
        person("foot", "🦶"),
        person("ear", "👂"),
        person("ear_with_hearing_aid", "🦻"),
        person("nose", "👃"),
        person("brain", "🧠"),
        person("anatomical_heart", "🫀"),
        person("lungs", "🫁"),
        person("tooth", "🦷"),
        person("bone", "🦴"),
        person("eyes", "👀"),
        person("eye", "👁️"),
        person("tongue", "👅"),
        person("lips", "👄"),
        person("biting_lip", "🫦"),
        person("baby", "👶"),
        person("child", "🧒"),
        person("boy", "👦"),
        person("girl", "👧"),
        person("adult", "🧑"),
        person("blond_haired_person", "👱"),
        person("man", "👨"),
        person("bearded_person", "🧔"),
        person("man_beard", "🧔‍♂️"),
        person("woman_beard", "🧔‍♀️"),
        person("red_haired_man", "👨‍🦰"),
        person("curly_haired_man", "👨‍🦱"),
        person("white_haired_man", "👨‍🦳"),
        person("bald_man", "👨‍🦲"),
        person("woman", "👩"),
        person("red_haired_woman", "👩‍🦰"),
        person("person_red_hair", "🧑‍🦰"),
        person("curly_haired_woman", "👩‍🦱"),
        person("person_curly_hair", "🧑‍🦱"),
        person("white_haired_woman", "👩‍🦳"),
        person("person_white_hair", "🧑‍🦳"),
        person("bald_woman", "👩‍🦲"),
        person("person_bald", "🧑‍🦲"),
        person("blond_haired_woman", "👱‍♀️", "blonde_woman"),
        person("blond_haired_man", "👱‍♂️"),
        person("older_adult", "🧓"),
        person("older_man", "👴"),
        person("older_woman", "👵"),
        person("frowning_person", "🙍"),
        person("frowning_man", "🙍‍♂️"),
        person("frowning_woman", "🙍‍♀️"),
        person("pouting_face", "🙎"),
        person("pouting_man", "🙎‍♂️"),
        person("pouting_woman", "🙎‍♀️"),
        person("no_good", "🙅"),
        person("no_good_man", "🙅‍♂️", "ng_man"),
        person("no_good_woman", "🙅‍♀️", "ng_woman"),
        person("ok_person", "🙆"),
        person("ok_man", "🙆‍♂️"),
        person("ok_woman", "🙆‍♀️"),
        person("tipping_hand_person", "💁", "information_desk_person"),
        person("tipping_hand_man", "💁‍♂️", "sassy_man"),
        person("tipping_hand_woman", "💁‍♀️", "sassy_woman"),
        person("raising_hand", "🙋"),
        person("raising_hand_man", "🙋‍♂️"),
        person("raising_hand_woman", "🙋‍♀️"),
        person("deaf_person", "🧏"),
        person("deaf_man", "🧏‍♂️"),
        person("deaf_woman", "🧏‍♀️"),
        person("bow", "🙇"),
        person("bowing_man", "🙇‍♂️"),
        person("bowing_woman", "🙇‍♀️"),
        person("facepalm", "🤦"),
        person("man_facepalming", "🤦‍♂️"),
        person("woman_facepalming", "🤦‍♀️"),
        person("shrug", "🤷"),
        person("man_shrugging", "🤷‍♂️"),
        person("woman_shrugging", "🤷‍♀️"),
        person("health_worker", "🧑‍⚕️"),
        person("man_health_worker", "👨‍⚕️"),
        person("woman_health_worker", "👩‍⚕️"),
        person("student", "🧑‍🎓"),
        person("man_student", "👨‍🎓"),
        person("woman_student", "👩‍🎓"),
        person("teacher", "🧑‍🏫"),
        person("man_teacher", "👨‍🏫"),
        person("woman_teacher", "👩‍🏫"),
        person("judge", "🧑‍⚖️"),
        person("man_judge", "👨‍⚖️"),
        person("woman_judge", "👩‍⚖️"),
        person("farmer", "🧑‍🌾"),
        person("man_farmer", "👨‍🌾"),
        person("woman_farmer", "👩‍🌾"),
        person("cook", "🧑‍🍳"),
        person("man_cook", "👨‍🍳"),
        person("woman_cook", "👩‍🍳"),
        person("mechanic", "🧑‍🔧"),
        person("man_mechanic", "👨‍🔧"),
        person("woman_mechanic", "👩‍🔧"),
        person("factory_worker", "🧑‍🏭"),
        person("man_factory_worker", "👨‍🏭"),
        person("woman_factory_worker", "👩‍🏭"),
        person("office_worker", "🧑‍💼"),
        person("man_office_worker", "👨‍💼"),
        person("woman_office_worker", "👩‍💼"),
        person("scientist", "🧑‍🔬"),
        person("man_scientist", "👨‍🔬"),
        person("woman_scientist", "👩‍🔬"),
        person("technologist", "🧑‍💻"),
        person("man_technologist", "👨‍💻"),
        person("woman_technologist", "👩‍💻"),
        person("singer", "🧑‍🎤"),
        person("man_singer", "👨‍🎤"),
        person("woman_singer", "👩‍🎤"),
        person("artist", "🧑‍🎨"),
        person("man_artist", "👨‍🎨"),
        person("woman_artist", "👩‍🎨"),
        person("pilot", "🧑‍✈️"),
        person("man_pilot", "👨‍✈️"),
        person("woman_pilot", "👩‍✈️"),
        person("astronaut", "🧑‍🚀"),
        person("man_astronaut", "👨‍🚀"),
        person("woman_astronaut", "👩‍🚀"),
        person("firefighter", "🧑‍🚒"),
        person("man_firefighter", "👨‍🚒"),
        person("woman_firefighter", "👩‍🚒"),
        person("police_officer", "👮", "cop"),
        person("policeman", "👮‍♂️"),
        person("policewoman", "👮‍♀️"),
        person("detective", "🕵️"),
        person("male_detective", "🕵️‍♂️"),
        person("female_detective", "🕵️‍♀️"),
        person("guard", "💂"),
        person("guardsman", "💂‍♂️"),
        person("guardswoman", "💂‍♀️"),
        person("ninja", "🥷"),
        person("construction_worker", "👷"),
        person("construction_worker_man", "👷‍♂️"),
        person("construction_worker_woman", "👷‍♀️"),
        person("person_with_crown", "🫅"),
        person("prince", "🤴"),
        person("princess", "👸"),
        person("person_with_turban", "👳"),
        person("man_with_turban", "👳‍♂️"),
        person("woman_with_turban", "👳‍♀️"),
        person("man_with_gua_pi_mao", "👲"),
        person("woman_with_headscarf", "🧕"),
        person("person_in_tuxedo", "🤵"),
        person("man_in_tuxedo", "🤵‍♂️"),
        person("woman_in_tuxedo", "🤵‍♀️"),
        person("person_with_veil", "👰"),
        person("man_with_veil", "👰‍♂️"),
        person("woman_with_veil", "👰‍♀️", "bride_with_veil"),
        person("pregnant_woman", "🤰"),
        person("pregnant_man", "🫃"),
        person("pregnant_person", "🫄"),
        person("breast_feeding", "🤱"),
        person("woman_feeding_baby", "👩‍🍼"),
        person("man_feeding_baby", "👨‍🍼"),
        person("person_feeding_baby", "🧑‍🍼"),
        person("angel", "👼"),
        person("santa", "🎅"),
        person("mrs_claus", "🤶"),
        person("mx_claus", "🧑‍🎄"),
        person("superhero", "🦸"),
        person("superhero_man", "🦸‍♂️"),
        person("superhero_woman", "🦸‍♀️"),
        person("supervillain", "🦹"),
        person("supervillain_man", "🦹‍♂️"),
        person("supervillain_woman", "🦹‍♀️"),
        person("mage", "🧙"),
        person("mage_man", "🧙‍♂️"),
        person("mage_woman", "🧙‍♀️"),
        person("fairy", "🧚"),
        person("fairy_man", "🧚‍♂️"),
        person("fairy_woman", "🧚‍♀️"),
        person("vampire", "🧛"),
        person("vampire_man", "🧛‍♂️"),
        person("vampire_woman", "🧛‍♀️"),
        person("merperson", "🧜"),
        person("merman", "🧜‍♂️"),
        person("mermaid", "🧜‍♀️"),
        person("elf", "🧝"),
        person("elf_man", "🧝‍♂️"),
        person("elf_woman", "🧝‍♀️"),
        person("genie", "🧞"),
        person("genie_man", "🧞‍♂️"),
        person("genie_woman", "🧞‍♀️"),
        person("zombie", "🧟"),
        person("zombie_man", "🧟‍♂️"),
        person("zombie_woman", "🧟‍♀️"),
        person("troll", "🧌"),
        person("massage", "💆"),
        person("massage_man", "💆‍♂️"),
        person("massage_woman", "💆‍♀️"),
        person("haircut", "💇"),
        person("haircut_man", "💇‍♂️"),
        person("haircut_woman", "💇‍♀️"),
        person("walking", "🚶"),
        person("walking_man", "🚶‍♂️"),
        person("walking_woman", "🚶‍♀️"),
        person("standing_person", "🧍"),
        person("standing_man", "🧍‍♂️"),
        person("standing_woman", "🧍‍♀️"),
        person("kneeling_person", "🧎"),
        person("kneeling_man", "🧎‍♂️"),
        person("kneeling_woman", "🧎‍♀️"),
        person("person_with_probing_cane", "🧑‍🦯"),
        person("man_with_probing_cane", "👨‍🦯"),
        person("woman_with_probing_cane", "👩‍🦯"),
        person("person_in_motorized_wheelchair", "🧑‍🦼"),
        person("man_in_motorized_wheelchair", "👨‍🦼"),
        person("woman_in_motorized_wheelchair", "👩‍🦼"),
        person("person_in_manual_wheelchair", "🧑‍🦽"),
        person("man_in_manual_wheelchair", "👨‍🦽"),
        person("woman_in_manual_wheelchair", "👩‍🦽"),
        person("runner", "🏃", "running"),
        person("running_man", "🏃‍♂️"),
        person("running_woman", "🏃‍♀️"),
        person("woman_dancing", "💃", "dancer"),
        person("man_dancing", "🕺"),
        person("business_suit_levitating", "🕴️"),
        person("dancers", "👯"),
        person("dancing_men", "👯‍♂️"),
        person("dancing_women", "👯‍♀️"),
        person("sauna_person", "🧖"),
        person("sauna_man", "🧖‍♂️"),
        person("sauna_woman", "🧖‍♀️"),
        person("climbing", "🧗"),
        person("climbing_man", "🧗‍♂️"),
        person("climbing_woman", "🧗‍♀️"),
        person("person_fencing", "🤺"),
        person("horse_racing", "🏇"),
        person("skier", "⛷️"),
        person("snowboarder", "🏂"),
        person("golfing", "🏌️"),
        person("golfing_man", "🏌️‍♂️"),
        person("golfing_woman", "🏌️‍♀️"),
        person("surfer", "🏄"),
        person("surfing_man", "🏄‍♂️"),
        person("surfing_woman", "🏄‍♀️"),
        person("rowboat", "🚣"),
        person("rowing_man", "🚣‍♂️"),
        person("rowing_woman", "🚣‍♀️"),
        person("swimmer", "🏊"),
        person("swimming_man", "🏊‍♂️"),
        person("swimming_woman", "🏊‍♀️"),
        person("bouncing_ball_person", "⛹️"),
        person("bouncing_ball_man", "⛹️‍♂️", "basketball_man"),
        person("bouncing_ball_woman", "⛹️‍♀️", "basketball_woman"),
        person("weight_lifting", "🏋️"),
        person("weight_lifting_man", "🏋️‍♂️"),
        person("weight_lifting_woman", "🏋️‍♀️"),
        person("bicyclist", "🚴"),
        person("biking_man", "🚴‍♂️"),
        person("biking_woman", "🚴‍♀️"),
        person("mountain_bicyclist", "🚵"),
        person("mountain_biking_man", "🚵‍♂️"),
        person("mountain_biking_woman", "🚵‍♀️"),
        person("cartwheeling", "🤸"),
        person("man_cartwheeling", "🤸‍♂️"),
        person("woman_cartwheeling", "🤸‍♀️"),
        person("wrestling", "🤼"),
        person("men_wrestling", "🤼‍♂️"),
        person("women_wrestling", "🤼‍♀️"),
        person("water_polo", "🤽"),
        person("man_playing_water_polo", "🤽‍♂️"),
        person("woman_playing_water_polo", "🤽‍♀️"),
        person("handball_person", "🤾"),
        person("man_playing_handball", "🤾‍♂️"),
        person("woman_playing_handball", "🤾‍♀️"),
        person("juggling_person", "🤹"),
        person("man_juggling", "🤹‍♂️"),
        person("woman_juggling", "🤹‍♀️"),
        person("lotus_position", "🧘"),
        person("lotus_position_man", "🧘‍♂️"),
        person("lotus_position_woman", "🧘‍♀️"),
        person("bath", "🛀"),
        person("sleeping_bed", "🛌"),
        person("people_holding_hands", "🧑‍🤝‍🧑"),
        person("two_women_holding_hands", "👭"),
        person("couple", "👫"),
        person("two_men_holding_hands", "👬"),
        person("couplekiss", "💏"),
        person("couplekiss_man_woman", "👩‍❤️‍💋‍👨"),
        person("couplekiss_man_man", "👨‍❤️‍💋‍👨"),
        person("couplekiss_woman_woman", "👩‍❤️‍💋‍👩"),
        person("couple_with_heart", "💑"),
        person("couple_with_heart_woman_man", "👩‍❤️‍👨"),
        person("couple_with_heart_man_man", "👨‍❤️‍👨"),
        person("couple_with_heart_woman_woman", "👩‍❤️‍👩"),
        person("family", "👪"),
        person("family_man_woman_boy", "👨‍👩‍👦"),
        person("family_man_woman_girl", "👨‍👩‍👧"),
        person("family_man_woman_girl_boy", "👨‍👩‍👧‍👦"),
        person("family_man_woman_boy_boy", "👨‍👩‍👦‍👦"),
        person("family_man_woman_girl_girl", "👨‍👩‍👧‍👧"),
        person("family_man_man_boy", "👨‍👨‍👦"),
        person("family_man_man_girl", "👨‍👨‍👧"),
        person("family_man_man_girl_boy", "👨‍👨‍👧‍👦"),
        person("family_man_man_boy_boy", "👨‍👨‍👦‍👦"),
        person("family_man_man_girl_girl", "👨‍👨‍👧‍👧"),
        person("family_woman_woman_boy", "👩‍👩‍👦"),
        person("family_woman_woman_girl", "👩‍👩‍👧"),
        person("family_woman_woman_girl_boy", "👩‍👩‍👧‍👦"),
        person("family_woman_woman_boy_boy", "👩‍👩‍👦‍👦"),
        person("family_woman_woman_girl_girl", "👩‍👩‍👧‍👧"),
        person("family_man_boy", "👨‍👦"),
        person("family_man_boy_boy", "👨‍👦‍👦"),
        person("family_man_girl", "👨‍👧"),
        person("family_man_girl_boy", "👨‍👧‍👦"),
        person("family_man_girl_girl", "👨‍👧‍👧"),
        person("family_woman_boy", "👩‍👦"),
        person("family_woman_boy_boy", "👩‍👦‍👦"),
        person("family_woman_girl", "👩‍👧"),
        person("family_woman_girl_boy", "👩‍👧‍👦"),
        person("family_woman_girl_girl", "👩‍👧‍👧"),
        person("speaking_head", "🗣️"),
        person("bust_in_silhouette", "👤"),
        person("busts_in_silhouette", "👥"),
        person("people_hugging", "🫂"),
        person("footprints", "👣"),
    )

    private val animals: List<EmojiPickerItem> = listOf(
        animal("monkey_face", "🐵"),
        animal("monkey", "🐒"),
        animal("gorilla", "🦍"),
        animal("orangutan", "🦧"),
        animal("dog", "🐶"),
        animal("dog2", "🐕"),
        animal("guide_dog", "🦮"),
        animal("service_dog", "🐕‍🦺"),
        animal("poodle", "🐩"),
        animal("wolf", "🐺"),
        animal("fox_face", "🦊"),
        animal("raccoon", "🦝"),
        animal("cat", "🐱"),
        animal("cat2", "🐈"),
        animal("black_cat", "🐈‍⬛"),
        animal("lion", "🦁"),
        animal("tiger", "🐯"),
        animal("tiger2", "🐅"),
        animal("leopard", "🐆"),
        animal("horse", "🐴"),
        animal("moose", "🫎"),
        animal("donkey", "🫏"),
        animal("racehorse", "🐎"),
        animal("unicorn", "🦄"),
        animal("zebra", "🦓"),
        animal("deer", "🦌"),
        animal("bison", "🦬"),
        animal("cow", "🐮"),
        animal("ox", "🐂"),
        animal("water_buffalo", "🐃"),
        animal("cow2", "🐄"),
        animal("pig", "🐷"),
        animal("pig2", "🐖"),
        animal("boar", "🐗"),
        animal("pig_nose", "🐽"),
        animal("ram", "🐏"),
        animal("sheep", "🐑"),
        animal("goat", "🐐"),
        animal("dromedary_camel", "🐪"),
        animal("camel", "🐫"),
        animal("llama", "🦙"),
        animal("giraffe", "🦒"),
        animal("elephant", "🐘"),
        animal("mammoth", "🦣"),
        animal("rhinoceros", "🦏"),
        animal("hippopotamus", "🦛"),
        animal("mouse", "🐭"),
        animal("mouse2", "🐁"),
        animal("rat", "🐀"),
        animal("hamster", "🐹"),
        animal("rabbit", "🐰"),
        animal("rabbit2", "🐇"),
        animal("chipmunk", "🐿️"),
        animal("beaver", "🦫"),
        animal("hedgehog", "🦔"),
        animal("bat", "🦇"),
        animal("bear", "🐻"),
        animal("polar_bear", "🐻‍❄️"),
        animal("koala", "🐨"),
        animal("panda_face", "🐼"),
        animal("sloth", "🦥"),
        animal("otter", "🦦"),
        animal("skunk", "🦨"),
        animal("kangaroo", "🦘"),
        animal("badger", "🦡"),
        animal("feet", "🐾", "paw_prints"),
        animal("turkey", "🦃"),
        animal("chicken", "🐔"),
        animal("rooster", "🐓"),
        animal("hatching_chick", "🐣"),
        animal("baby_chick", "🐤"),
        animal("hatched_chick", "🐥"),
        animal("bird", "🐦"),
        animal("penguin", "🐧"),
        animal("dove", "🕊️"),
        animal("eagle", "🦅"),
        animal("duck", "🦆"),
        animal("swan", "🦢"),
        animal("owl", "🦉"),
        animal("dodo", "🦤"),
        animal("feather", "🪶"),
        animal("flamingo", "🦩"),
        animal("peacock", "🦚"),
        animal("parrot", "🦜"),
        animal("wing", "🪽"),
        animal("black_bird", "🐦‍⬛"),
        animal("goose", "🪿"),
        animal("frog", "🐸"),
        animal("crocodile", "🐊"),
        animal("turtle", "🐢"),
        animal("lizard", "🦎"),
        animal("snake", "🐍"),
        animal("dragon_face", "🐲"),
        animal("dragon", "🐉"),
        animal("sauropod", "🦕"),
        animal("t-rex", "🦖"),
        animal("whale", "🐳"),
        animal("whale2", "🐋"),
        animal("dolphin", "🐬", "flipper"),
        animal("seal", "🦭"),
        animal("fish", "🐟"),
        animal("tropical_fish", "🐠"),
        animal("blowfish", "🐡"),
        animal("shark", "🦈"),
        animal("octopus", "🐙"),
        animal("shell", "🐚"),
        animal("coral", "🪸"),
        animal("jellyfish", "🪼"),
        animal("snail", "🐌"),
        animal("butterfly", "🦋"),
        animal("bug", "🐛"),
        animal("ant", "🐜"),
        animal("bee", "🐝", "honeybee"),
        animal("beetle", "🪲"),
        animal("lady_beetle", "🐞"),
        animal("cricket", "🦗"),
        animal("cockroach", "🪳"),
        animal("spider", "🕷️"),
        animal("spider_web", "🕸️"),
        animal("scorpion", "🦂"),
        animal("mosquito", "🦟"),
        animal("fly", "🪰"),
        animal("worm", "🪱"),
        animal("microbe", "🦠"),
        animal("bouquet", "💐"),
        animal("cherry_blossom", "🌸"),
        animal("white_flower", "💮"),
        animal("lotus", "🪷"),
        animal("rosette", "🏵️"),
        animal("rose", "🌹"),
        animal("wilted_flower", "🥀"),
        animal("hibiscus", "🌺"),
        animal("sunflower", "🌻"),
        animal("blossom", "🌼"),
        animal("tulip", "🌷"),
        animal("hyacinth", "🪻"),
        animal("seedling", "🌱"),
        animal("potted_plant", "🪴"),
        animal("evergreen_tree", "🌲"),
        animal("deciduous_tree", "🌳"),
        animal("palm_tree", "🌴"),
        animal("cactus", "🌵"),
        animal("ear_of_rice", "🌾"),
        animal("herb", "🌿"),
        animal("shamrock", "☘️"),
        animal("four_leaf_clover", "🍀"),
        animal("maple_leaf", "🍁"),
        animal("fallen_leaf", "🍂"),
        animal("leaves", "🍃"),
        animal("empty_nest", "🪹"),
        animal("nest_with_eggs", "🪺"),
        animal("mushroom", "🍄"),
    )

    private val food: List<EmojiPickerItem> = listOf(
        foodItem("grapes", "🍇"),
        foodItem("melon", "🍈"),
        foodItem("watermelon", "🍉"),
        foodItem("tangerine", "🍊", "orange", "mandarin"),
        foodItem("lemon", "🍋"),
        foodItem("banana", "🍌"),
        foodItem("pineapple", "🍍"),
        foodItem("mango", "🥭"),
        foodItem("apple", "🍎"),
        foodItem("green_apple", "🍏"),
        foodItem("pear", "🍐"),
        foodItem("peach", "🍑"),
        foodItem("cherries", "🍒"),
        foodItem("strawberry", "🍓"),
        foodItem("blueberries", "🫐"),
        foodItem("kiwi_fruit", "🥝"),
        foodItem("tomato", "🍅"),
        foodItem("olive", "🫒"),
        foodItem("coconut", "🥥"),
        foodItem("avocado", "🥑"),
        foodItem("eggplant", "🍆"),
        foodItem("potato", "🥔"),
        foodItem("carrot", "🥕"),
        foodItem("corn", "🌽"),
        foodItem("hot_pepper", "🌶️"),
        foodItem("bell_pepper", "🫑"),
        foodItem("cucumber", "🥒"),
        foodItem("leafy_green", "🥬"),
        foodItem("broccoli", "🥦"),
        foodItem("garlic", "🧄"),
        foodItem("onion", "🧅"),
        foodItem("peanuts", "🥜"),
        foodItem("beans", "🫘"),
        foodItem("chestnut", "🌰"),
        foodItem("ginger_root", "🫚"),
        foodItem("pea_pod", "🫛"),
        foodItem("bread", "🍞"),
        foodItem("croissant", "🥐"),
        foodItem("baguette_bread", "🥖"),
        foodItem("flatbread", "🫓"),
        foodItem("pretzel", "🥨"),
        foodItem("bagel", "🥯"),
        foodItem("pancakes", "🥞"),
        foodItem("waffle", "🧇"),
        foodItem("cheese", "🧀"),
        foodItem("meat_on_bone", "🍖"),
        foodItem("poultry_leg", "🍗"),
        foodItem("cut_of_meat", "🥩"),
        foodItem("bacon", "🥓"),
        foodItem("hamburger", "🍔"),
        foodItem("fries", "🍟"),
        foodItem("pizza", "🍕"),
        foodItem("hotdog", "🌭"),
        foodItem("sandwich", "🥪"),
        foodItem("taco", "🌮"),
        foodItem("burrito", "🌯"),
        foodItem("tamale", "🫔"),
        foodItem("stuffed_flatbread", "🥙"),
        foodItem("falafel", "🧆"),
        foodItem("egg", "🥚"),
        foodItem("fried_egg", "🍳"),
        foodItem("shallow_pan_of_food", "🥘"),
        foodItem("stew", "🍲"),
        foodItem("fondue", "🫕"),
        foodItem("bowl_with_spoon", "🥣"),
        foodItem("green_salad", "🥗"),
        foodItem("popcorn", "🍿"),
        foodItem("butter", "🧈"),
        foodItem("salt", "🧂"),
        foodItem("canned_food", "🥫"),
        foodItem("bento", "🍱"),
        foodItem("rice_cracker", "🍘"),
        foodItem("rice_ball", "🍙"),
        foodItem("rice", "🍚"),
        foodItem("curry", "🍛"),
        foodItem("ramen", "🍜"),
        foodItem("spaghetti", "🍝"),
        foodItem("sweet_potato", "🍠"),
        foodItem("oden", "🍢"),
        foodItem("sushi", "🍣"),
        foodItem("fried_shrimp", "🍤"),
        foodItem("fish_cake", "🍥"),
        foodItem("moon_cake", "🥮"),
        foodItem("dango", "🍡"),
        foodItem("dumpling", "🥟"),
        foodItem("fortune_cookie", "🥠"),
        foodItem("takeout_box", "🥡"),
        foodItem("crab", "🦀"),
        foodItem("lobster", "🦞"),
        foodItem("shrimp", "🦐"),
        foodItem("squid", "🦑"),
        foodItem("oyster", "🦪"),
        foodItem("icecream", "🍦"),
        foodItem("shaved_ice", "🍧"),
        foodItem("ice_cream", "🍨"),
        foodItem("doughnut", "🍩"),
        foodItem("cookie", "🍪"),
        foodItem("birthday", "🎂"),
        foodItem("cake", "🍰"),
        foodItem("cupcake", "🧁"),
        foodItem("pie", "🥧"),
        foodItem("chocolate_bar", "🍫"),
        foodItem("candy", "🍬"),
        foodItem("lollipop", "🍭"),
        foodItem("custard", "🍮"),
        foodItem("honey_pot", "🍯"),
        foodItem("baby_bottle", "🍼"),
        foodItem("milk_glass", "🥛"),
        foodItem("coffee", "☕"),
        foodItem("teapot", "🫖"),
        foodItem("tea", "🍵"),
        foodItem("sake", "🍶"),
        foodItem("champagne", "🍾"),
        foodItem("wine_glass", "🍷"),
        foodItem("cocktail", "🍸"),
        foodItem("tropical_drink", "🍹"),
        foodItem("beer", "🍺"),
        foodItem("beers", "🍻"),
        foodItem("clinking_glasses", "🥂"),
        foodItem("tumbler_glass", "🥃"),
        foodItem("pouring_liquid", "🫗"),
        foodItem("cup_with_straw", "🥤"),
        foodItem("bubble_tea", "🧋"),
        foodItem("beverage_box", "🧃"),
        foodItem("mate", "🧉"),
        foodItem("ice_cube", "🧊"),
        foodItem("chopsticks", "🥢"),
        foodItem("plate_with_cutlery", "🍽️"),
        foodItem("fork_and_knife", "🍴"),
        foodItem("spoon", "🥄"),
        foodItem("hocho", "🔪", "knife"),
        foodItem("jar", "🫙"),
        foodItem("amphora", "🏺"),
    )

    private val travel: List<EmojiPickerItem> = listOf(
        travelItem("earth_africa", "🌍"),
        travelItem("earth_americas", "🌎"),
        travelItem("earth_asia", "🌏"),
        travelItem("globe_with_meridians", "🌐"),
        travelItem("world_map", "🗺️"),
        travelItem("japan", "🗾"),
        travelItem("compass", "🧭"),
        travelItem("mountain_snow", "🏔️"),
        travelItem("mountain", "⛰️"),
        travelItem("volcano", "🌋"),
        travelItem("mount_fuji", "🗻"),
        travelItem("camping", "🏕️"),
        travelItem("beach_umbrella", "🏖️"),
        travelItem("desert", "🏜️"),
        travelItem("desert_island", "🏝️"),
        travelItem("national_park", "🏞️"),
        travelItem("stadium", "🏟️"),
        travelItem("classical_building", "🏛️"),
        travelItem("building_construction", "🏗️"),
        travelItem("bricks", "🧱"),
        travelItem("rock", "🪨"),
        travelItem("wood", "🪵"),
        travelItem("hut", "🛖"),
        travelItem("houses", "🏘️"),
        travelItem("derelict_house", "🏚️"),
        travelItem("house", "🏠"),
        travelItem("house_with_garden", "🏡"),
        travelItem("office", "🏢"),
        travelItem("post_office", "🏣"),
        travelItem("european_post_office", "🏤"),
        travelItem("hospital", "🏥"),
        travelItem("bank", "🏦"),
        travelItem("hotel", "🏨"),
        travelItem("love_hotel", "🏩"),
        travelItem("convenience_store", "🏪"),
        travelItem("school", "🏫"),
        travelItem("department_store", "🏬"),
        travelItem("factory", "🏭"),
        travelItem("japanese_castle", "🏯"),
        travelItem("european_castle", "🏰"),
        travelItem("wedding", "💒"),
        travelItem("tokyo_tower", "🗼"),
        travelItem("statue_of_liberty", "🗽"),
        travelItem("church", "⛪"),
        travelItem("mosque", "🕌"),
        travelItem("hindu_temple", "🛕"),
        travelItem("synagogue", "🕍"),
        travelItem("shinto_shrine", "⛩️"),
        travelItem("kaaba", "🕋"),
        travelItem("fountain", "⛲"),
        travelItem("tent", "⛺"),
        travelItem("foggy", "🌁"),
        travelItem("night_with_stars", "🌃"),
        travelItem("cityscape", "🏙️"),
        travelItem("sunrise_over_mountains", "🌄"),
        travelItem("sunrise", "🌅"),
        travelItem("city_sunset", "🌆"),
        travelItem("city_sunrise", "🌇"),
        travelItem("bridge_at_night", "🌉"),
        travelItem("hotsprings", "♨️"),
        travelItem("carousel_horse", "🎠"),
        travelItem("playground_slide", "🛝"),
        travelItem("ferris_wheel", "🎡"),
        travelItem("roller_coaster", "🎢"),
        travelItem("barber", "💈"),
        travelItem("circus_tent", "🎪"),
        travelItem("steam_locomotive", "🚂"),
        travelItem("railway_car", "🚃"),
        travelItem("bullettrain_side", "🚄"),
        travelItem("bullettrain_front", "🚅"),
        travelItem("train2", "🚆"),
        travelItem("metro", "🚇"),
        travelItem("light_rail", "🚈"),
        travelItem("station", "🚉"),
        travelItem("tram", "🚊"),
        travelItem("monorail", "🚝"),
        travelItem("mountain_railway", "🚞"),
        travelItem("train", "🚋"),
        travelItem("bus", "🚌"),
        travelItem("oncoming_bus", "🚍"),
        travelItem("trolleybus", "🚎"),
        travelItem("minibus", "🚐"),
        travelItem("ambulance", "🚑"),
        travelItem("fire_engine", "🚒"),
        travelItem("police_car", "🚓"),
        travelItem("oncoming_police_car", "🚔"),
        travelItem("taxi", "🚕"),
        travelItem("oncoming_taxi", "🚖"),
        travelItem("car", "🚗", "red_car"),
        travelItem("oncoming_automobile", "🚘"),
        travelItem("blue_car", "🚙"),
        travelItem("pickup_truck", "🛻"),
        travelItem("truck", "🚚"),
        travelItem("articulated_lorry", "🚛"),
        travelItem("tractor", "🚜"),
        travelItem("racing_car", "🏎️"),
        travelItem("motorcycle", "🏍️"),
        travelItem("motor_scooter", "🛵"),
        travelItem("manual_wheelchair", "🦽"),
        travelItem("motorized_wheelchair", "🦼"),
        travelItem("auto_rickshaw", "🛺"),
        travelItem("bike", "🚲"),
        travelItem("kick_scooter", "🛴"),
        travelItem("skateboard", "🛹"),
        travelItem("roller_skate", "🛼"),
        travelItem("busstop", "🚏"),
        travelItem("motorway", "🛣️"),
        travelItem("railway_track", "🛤️"),
        travelItem("oil_drum", "🛢️"),
        travelItem("fuelpump", "⛽"),
        travelItem("wheel", "🛞"),
        travelItem("rotating_light", "🚨"),
        travelItem("traffic_light", "🚥"),
        travelItem("vertical_traffic_light", "🚦"),
        travelItem("stop_sign", "🛑"),
        travelItem("construction", "🚧"),
        travelItem("anchor", "⚓"),
        travelItem("ring_buoy", "🛟"),
        travelItem("boat", "⛵", "sailboat"),
        travelItem("canoe", "🛶"),
        travelItem("speedboat", "🚤"),
        travelItem("passenger_ship", "🛳️"),
        travelItem("ferry", "⛴️"),
        travelItem("motor_boat", "🛥️"),
        travelItem("ship", "🚢"),
        travelItem("airplane", "✈️"),
        travelItem("small_airplane", "🛩️"),
        travelItem("flight_departure", "🛫"),
        travelItem("flight_arrival", "🛬"),
        travelItem("parachute", "🪂"),
        travelItem("seat", "💺"),
        travelItem("helicopter", "🚁"),
        travelItem("suspension_railway", "🚟"),
        travelItem("mountain_cableway", "🚠"),
        travelItem("aerial_tramway", "🚡"),
        travelItem("artificial_satellite", "🛰️"),
        travelItem("rocket", "🚀"),
        travelItem("flying_saucer", "🛸"),
        travelItem("bellhop_bell", "🛎️"),
        travelItem("luggage", "🧳"),
        travelItem("hourglass", "⌛"),
        travelItem("hourglass_flowing_sand", "⏳"),
        travelItem("watch", "⌚"),
        travelItem("alarm_clock", "⏰"),
        travelItem("stopwatch", "⏱️"),
        travelItem("timer_clock", "⏲️"),
        travelItem("mantelpiece_clock", "🕰️"),
        travelItem("clock12", "🕛"),
        travelItem("clock1230", "🕧"),
        travelItem("clock1", "🕐"),
        travelItem("clock130", "🕜"),
        travelItem("clock2", "🕑"),
        travelItem("clock230", "🕝"),
        travelItem("clock3", "🕒"),
        travelItem("clock330", "🕞"),
        travelItem("clock4", "🕓"),
        travelItem("clock430", "🕟"),
        travelItem("clock5", "🕔"),
        travelItem("clock530", "🕠"),
        travelItem("clock6", "🕕"),
        travelItem("clock630", "🕡"),
        travelItem("clock7", "🕖"),
        travelItem("clock730", "🕢"),
        travelItem("clock8", "🕗"),
        travelItem("clock830", "🕣"),
        travelItem("clock9", "🕘"),
        travelItem("clock930", "🕤"),
        travelItem("clock10", "🕙"),
        travelItem("clock1030", "🕥"),
        travelItem("clock11", "🕚"),
        travelItem("clock1130", "🕦"),
        travelItem("new_moon", "🌑"),
        travelItem("waxing_crescent_moon", "🌒"),
        travelItem("first_quarter_moon", "🌓"),
        travelItem("moon", "🌔", "waxing_gibbous_moon"),
        travelItem("full_moon", "🌕"),
        travelItem("waning_gibbous_moon", "🌖"),
        travelItem("last_quarter_moon", "🌗"),
        travelItem("waning_crescent_moon", "🌘"),
        travelItem("crescent_moon", "🌙"),
        travelItem("new_moon_with_face", "🌚"),
        travelItem("first_quarter_moon_with_face", "🌛"),
        travelItem("last_quarter_moon_with_face", "🌜"),
        travelItem("thermometer", "🌡️"),
        travelItem("sunny", "☀️"),
        travelItem("full_moon_with_face", "🌝"),
        travelItem("sun_with_face", "🌞"),
        travelItem("ringed_planet", "🪐"),
        travelItem("star", "⭐"),
        travelItem("star2", "🌟"),
        travelItem("stars", "🌠"),
        travelItem("milky_way", "🌌"),
        travelItem("cloud", "☁️"),
        travelItem("partly_sunny", "⛅"),
        travelItem("cloud_with_lightning_and_rain", "⛈️"),
        travelItem("sun_behind_small_cloud", "🌤️"),
        travelItem("sun_behind_large_cloud", "🌥️"),
        travelItem("sun_behind_rain_cloud", "🌦️"),
        travelItem("cloud_with_rain", "🌧️"),
        travelItem("cloud_with_snow", "🌨️"),
        travelItem("cloud_with_lightning", "🌩️"),
        travelItem("tornado", "🌪️"),
        travelItem("fog", "🌫️"),
        travelItem("wind_face", "🌬️"),
        travelItem("cyclone", "🌀"),
        travelItem("rainbow", "🌈"),
        travelItem("closed_umbrella", "🌂"),
        travelItem("open_umbrella", "☂️"),
        travelItem("umbrella", "☔"),
        travelItem("parasol_on_ground", "⛱️"),
        travelItem("zap", "⚡"),
        travelItem("snowflake", "❄️"),
        travelItem("snowman_with_snow", "☃️"),
        travelItem("snowman", "⛄"),
        travelItem("comet", "☄️"),
        travelItem("fire", "🔥"),
        travelItem("droplet", "💧"),
        travelItem("ocean", "🌊"),
    )

    private val activities: List<EmojiPickerItem> = listOf(
        activity("jack_o_lantern", "🎃"),
        activity("christmas_tree", "🎄"),
        activity("fireworks", "🎆"),
        activity("sparkler", "🎇"),
        activity("firecracker", "🧨"),
        activity("sparkles", "✨"),
        activity("balloon", "🎈"),
        activity("tada", "🎉"),
        activity("confetti_ball", "🎊"),
        activity("tanabata_tree", "🎋"),
        activity("bamboo", "🎍"),
        activity("dolls", "🎎"),
        activity("flags", "🎏"),
        activity("wind_chime", "🎐"),
        activity("rice_scene", "🎑"),
        activity("red_envelope", "🧧"),
        activity("ribbon", "🎀"),
        activity("gift", "🎁"),
        activity("reminder_ribbon", "🎗️"),
        activity("tickets", "🎟️"),
        activity("ticket", "🎫"),
        activity("medal_military", "🎖️"),
        activity("trophy", "🏆"),
        activity("medal_sports", "🏅"),
        activity("1st_place_medal", "🥇"),
        activity("2nd_place_medal", "🥈"),
        activity("3rd_place_medal", "🥉"),
        activity("soccer", "⚽"),
        activity("baseball", "⚾"),
        activity("softball", "🥎"),
        activity("basketball", "🏀"),
        activity("volleyball", "🏐"),
        activity("football", "🏈"),
        activity("rugby_football", "🏉"),
        activity("tennis", "🎾"),
        activity("flying_disc", "🥏"),
        activity("bowling", "🎳"),
        activity("cricket_game", "🏏"),
        activity("field_hockey", "🏑"),
        activity("ice_hockey", "🏒"),
        activity("lacrosse", "🥍"),
        activity("ping_pong", "🏓"),
        activity("badminton", "🏸"),
        activity("boxing_glove", "🥊"),
        activity("martial_arts_uniform", "🥋"),
        activity("goal_net", "🥅"),
        activity("golf", "⛳"),
        activity("ice_skate", "⛸️"),
        activity("fishing_pole_and_fish", "🎣"),
        activity("diving_mask", "🤿"),
        activity("running_shirt_with_sash", "🎽"),
        activity("ski", "🎿"),
        activity("sled", "🛷"),
        activity("curling_stone", "🥌"),
        activity("dart", "🎯"),
        activity("yo_yo", "🪀"),
        activity("kite", "🪁"),
        activity("gun", "🔫"),
        activity("8ball", "🎱"),
        activity("crystal_ball", "🔮"),
        activity("magic_wand", "🪄"),
        activity("video_game", "🎮"),
        activity("joystick", "🕹️"),
        activity("slot_machine", "🎰"),
        activity("game_die", "🎲"),
        activity("jigsaw", "🧩"),
        activity("teddy_bear", "🧸"),
        activity("pinata", "🪅"),
        activity("mirror_ball", "🪩"),
        activity("nesting_dolls", "🪆"),
        activity("spades", "♠️"),
        activity("hearts", "♥️"),
        activity("diamonds", "♦️"),
        activity("clubs", "♣️"),
        activity("chess_pawn", "♟️"),
        activity("black_joker", "🃏"),
        activity("mahjong", "🀄"),
        activity("flower_playing_cards", "🎴"),
        activity("performing_arts", "🎭"),
        activity("framed_picture", "🖼️"),
        activity("art", "🎨"),
        activity("thread", "🧵"),
        activity("sewing_needle", "🪡"),
        activity("yarn", "🧶"),
        activity("knot", "🪢"),
    )

    private val objects: List<EmojiPickerItem> = listOf(
        objectItem("eyeglasses", "👓"),
        objectItem("dark_sunglasses", "🕶️"),
        objectItem("goggles", "🥽"),
        objectItem("lab_coat", "🥼"),
        objectItem("safety_vest", "🦺"),
        objectItem("necktie", "👔"),
        objectItem("shirt", "👕", "tshirt"),
        objectItem("jeans", "👖"),
        objectItem("scarf", "🧣"),
        objectItem("gloves", "🧤"),
        objectItem("coat", "🧥"),
        objectItem("socks", "🧦"),
        objectItem("dress", "👗"),
        objectItem("kimono", "👘"),
        objectItem("sari", "🥻"),
        objectItem("one_piece_swimsuit", "🩱"),
        objectItem("swim_brief", "🩲"),
        objectItem("shorts", "🩳"),
        objectItem("bikini", "👙"),
        objectItem("womans_clothes", "👚"),
        objectItem("folding_hand_fan", "🪭"),
        objectItem("purse", "👛"),
        objectItem("handbag", "👜"),
        objectItem("pouch", "👝"),
        objectItem("shopping", "🛍️"),
        objectItem("school_satchel", "🎒"),
        objectItem("thong_sandal", "🩴"),
        objectItem("mans_shoe", "👞", "shoe"),
        objectItem("athletic_shoe", "👟"),
        objectItem("hiking_boot", "🥾"),
        objectItem("flat_shoe", "🥿"),
        objectItem("high_heel", "👠"),
        objectItem("sandal", "👡"),
        objectItem("ballet_shoes", "🩰"),
        objectItem("boot", "👢"),
        objectItem("hair_pick", "🪮"),
        objectItem("crown", "👑"),
        objectItem("womans_hat", "👒"),
        objectItem("tophat", "🎩"),
        objectItem("mortar_board", "🎓"),
        objectItem("billed_cap", "🧢"),
        objectItem("military_helmet", "🪖"),
        objectItem("rescue_worker_helmet", "⛑️"),
        objectItem("prayer_beads", "📿"),
        objectItem("lipstick", "💄"),
        objectItem("ring", "💍"),
        objectItem("gem", "💎"),
        objectItem("mute", "🔇"),
        objectItem("speaker", "🔈"),
        objectItem("sound", "🔉"),
        objectItem("loud_sound", "🔊"),
        objectItem("loudspeaker", "📢"),
        objectItem("mega", "📣"),
        objectItem("postal_horn", "📯"),
        objectItem("bell", "🔔"),
        objectItem("no_bell", "🔕"),
        objectItem("musical_score", "🎼"),
        objectItem("musical_note", "🎵"),
        objectItem("notes", "🎶"),
        objectItem("studio_microphone", "🎙️"),
        objectItem("level_slider", "🎚️"),
        objectItem("control_knobs", "🎛️"),
        objectItem("microphone", "🎤"),
        objectItem("headphones", "🎧"),
        objectItem("radio", "📻"),
        objectItem("saxophone", "🎷"),
        objectItem("accordion", "🪗"),
        objectItem("guitar", "🎸"),
        objectItem("musical_keyboard", "🎹"),
        objectItem("trumpet", "🎺"),
        objectItem("violin", "🎻"),
        objectItem("banjo", "🪕"),
        objectItem("drum", "🥁"),
        objectItem("long_drum", "🪘"),
        objectItem("maracas", "🪇"),
        objectItem("flute", "🪈"),
        objectItem("iphone", "📱"),
        objectItem("calling", "📲"),
        objectItem("phone", "☎️", "telephone"),
        objectItem("telephone_receiver", "📞"),
        objectItem("pager", "📟"),
        objectItem("fax", "📠"),
        objectItem("battery", "🔋"),
        objectItem("low_battery", "🪫"),
        objectItem("electric_plug", "🔌"),
        objectItem("computer", "💻"),
        objectItem("desktop_computer", "🖥️"),
        objectItem("printer", "🖨️"),
        objectItem("keyboard", "⌨️"),
        objectItem("computer_mouse", "🖱️"),
        objectItem("trackball", "🖲️"),
        objectItem("minidisc", "💽"),
        objectItem("floppy_disk", "💾"),
        objectItem("cd", "💿"),
        objectItem("dvd", "📀"),
        objectItem("abacus", "🧮"),
        objectItem("movie_camera", "🎥"),
        objectItem("film_strip", "🎞️"),
        objectItem("film_projector", "📽️"),
        objectItem("clapper", "🎬"),
        objectItem("tv", "📺"),
        objectItem("camera", "📷"),
        objectItem("camera_flash", "📸"),
        objectItem("video_camera", "📹"),
        objectItem("vhs", "📼"),
        objectItem("mag", "🔍"),
        objectItem("mag_right", "🔎"),
        objectItem("candle", "🕯️"),
        objectItem("bulb", "💡"),
        objectItem("flashlight", "🔦"),
        objectItem("izakaya_lantern", "🏮", "lantern"),
        objectItem("diya_lamp", "🪔"),
        objectItem("notebook_with_decorative_cover", "📔"),
        objectItem("closed_book", "📕"),
        objectItem("book", "📖", "open_book"),
        objectItem("green_book", "📗"),
        objectItem("blue_book", "📘"),
        objectItem("orange_book", "📙"),
        objectItem("books", "📚"),
        objectItem("notebook", "📓"),
        objectItem("ledger", "📒"),
        objectItem("page_with_curl", "📃"),
        objectItem("scroll", "📜"),
        objectItem("page_facing_up", "📄"),
        objectItem("newspaper", "📰"),
        objectItem("newspaper_roll", "🗞️"),
        objectItem("bookmark_tabs", "📑"),
        objectItem("bookmark", "🔖"),
        objectItem("label", "🏷️"),
        objectItem("moneybag", "💰"),
        objectItem("coin", "🪙"),
        objectItem("yen", "💴"),
        objectItem("dollar", "💵"),
        objectItem("euro", "💶"),
        objectItem("pound", "💷"),
        objectItem("money_with_wings", "💸"),
        objectItem("credit_card", "💳"),
        objectItem("receipt", "🧾"),
        objectItem("chart", "💹"),
        objectItem("envelope", "✉️"),
        objectItem("email", "📧", "e-mail"),
        objectItem("incoming_envelope", "📨"),
        objectItem("envelope_with_arrow", "📩"),
        objectItem("outbox_tray", "📤"),
        objectItem("inbox_tray", "📥"),
        objectItem("package", "📦"),
        objectItem("mailbox", "📫"),
        objectItem("mailbox_closed", "📪"),
        objectItem("mailbox_with_mail", "📬"),
        objectItem("mailbox_with_no_mail", "📭"),
        objectItem("postbox", "📮"),
        objectItem("ballot_box", "🗳️"),
        objectItem("pencil2", "✏️"),
        objectItem("black_nib", "✒️"),
        objectItem("fountain_pen", "🖋️"),
        objectItem("pen", "🖊️"),
        objectItem("paintbrush", "🖌️"),
        objectItem("crayon", "🖍️"),
        objectItem("memo", "📝", "pencil"),
        objectItem("briefcase", "💼"),
        objectItem("file_folder", "📁"),
        objectItem("open_file_folder", "📂"),
        objectItem("card_index_dividers", "🗂️"),
        objectItem("date", "📅"),
        objectItem("calendar", "📆"),
        objectItem("spiral_notepad", "🗒️"),
        objectItem("spiral_calendar", "🗓️"),
        objectItem("card_index", "📇"),
        objectItem("chart_with_upwards_trend", "📈"),
        objectItem("chart_with_downwards_trend", "📉"),
        objectItem("bar_chart", "📊"),
        objectItem("clipboard", "📋"),
        objectItem("pushpin", "📌"),
        objectItem("round_pushpin", "📍"),
        objectItem("paperclip", "📎"),
        objectItem("paperclips", "🖇️"),
        objectItem("straight_ruler", "📏"),
        objectItem("triangular_ruler", "📐"),
        objectItem("scissors", "✂️"),
        objectItem("card_file_box", "🗃️"),
        objectItem("file_cabinet", "🗄️"),
        objectItem("wastebasket", "🗑️"),
        objectItem("lock", "🔒"),
        objectItem("unlock", "🔓"),
        objectItem("lock_with_ink_pen", "🔏"),
        objectItem("closed_lock_with_key", "🔐"),
        objectItem("key", "🔑"),
        objectItem("old_key", "🗝️"),
        objectItem("hammer", "🔨"),
        objectItem("axe", "🪓"),
        objectItem("pick", "⛏️"),
        objectItem("hammer_and_pick", "⚒️"),
        objectItem("hammer_and_wrench", "🛠️"),
        objectItem("dagger", "🗡️"),
        objectItem("crossed_swords", "⚔️"),
        objectItem("bomb", "💣"),
        objectItem("boomerang", "🪃"),
        objectItem("bow_and_arrow", "🏹"),
        objectItem("shield", "🛡️"),
        objectItem("carpentry_saw", "🪚"),
        objectItem("wrench", "🔧"),
        objectItem("screwdriver", "🪛"),
        objectItem("nut_and_bolt", "🔩"),
        objectItem("gear", "⚙️"),
        objectItem("clamp", "🗜️"),
        objectItem("balance_scale", "⚖️"),
        objectItem("probing_cane", "🦯"),
        objectItem("link", "🔗"),
        objectItem("chains", "⛓️"),
        objectItem("hook", "🪝"),
        objectItem("toolbox", "🧰"),
        objectItem("magnet", "🧲"),
        objectItem("ladder", "🪜"),
        objectItem("alembic", "⚗️"),
        objectItem("test_tube", "🧪"),
        objectItem("petri_dish", "🧫"),
        objectItem("dna", "🧬"),
        objectItem("microscope", "🔬"),
        objectItem("telescope", "🔭"),
        objectItem("satellite", "📡"),
        objectItem("syringe", "💉"),
        objectItem("drop_of_blood", "🩸"),
        objectItem("pill", "💊"),
        objectItem("adhesive_bandage", "🩹"),
        objectItem("crutch", "🩼"),
        objectItem("stethoscope", "🩺"),
        objectItem("x_ray", "🩻"),
        objectItem("door", "🚪"),
        objectItem("elevator", "🛗"),
        objectItem("mirror", "🪞"),
        objectItem("window", "🪟"),
        objectItem("bed", "🛏️"),
        objectItem("couch_and_lamp", "🛋️"),
        objectItem("chair", "🪑"),
        objectItem("toilet", "🚽"),
        objectItem("plunger", "🪠"),
        objectItem("shower", "🚿"),
        objectItem("bathtub", "🛁"),
        objectItem("mouse_trap", "🪤"),
        objectItem("razor", "🪒"),
        objectItem("lotion_bottle", "🧴"),
        objectItem("safety_pin", "🧷"),
        objectItem("broom", "🧹"),
        objectItem("basket", "🧺"),
        objectItem("roll_of_paper", "🧻"),
        objectItem("bucket", "🪣"),
        objectItem("soap", "🧼"),
        objectItem("bubbles", "🫧"),
        objectItem("toothbrush", "🪥"),
        objectItem("sponge", "🧽"),
        objectItem("fire_extinguisher", "🧯"),
        objectItem("shopping_cart", "🛒"),
        objectItem("smoking", "🚬"),
        objectItem("coffin", "⚰️"),
        objectItem("headstone", "🪦"),
        objectItem("funeral_urn", "⚱️"),
        objectItem("nazar_amulet", "🧿"),
        objectItem("hamsa", "🪬"),
        objectItem("moyai", "🗿"),
        objectItem("placard", "🪧"),
        objectItem("identification_card", "🪪"),
    )

    private val symbols: List<EmojiPickerItem> = listOf(
        symbol("atm", "🏧"),
        symbol("put_litter_in_its_place", "🚮"),
        symbol("potable_water", "🚰"),
        symbol("wheelchair", "♿"),
        symbol("mens", "🚹"),
        symbol("womens", "🚺"),
        symbol("restroom", "🚻"),
        symbol("baby_symbol", "🚼"),
        symbol("wc", "🚾"),
        symbol("passport_control", "🛂"),
        symbol("customs", "🛃"),
        symbol("baggage_claim", "🛄"),
        symbol("left_luggage", "🛅"),
        symbol("warning", "⚠️"),
        symbol("children_crossing", "🚸"),
        symbol("no_entry", "⛔"),
        symbol("no_entry_sign", "🚫"),
        symbol("no_bicycles", "🚳"),
        symbol("no_smoking", "🚭"),
        symbol("do_not_litter", "🚯"),
        symbol("non-potable_water", "🚱"),
        symbol("no_pedestrians", "🚷"),
        symbol("no_mobile_phones", "📵"),
        symbol("underage", "🔞"),
        symbol("radioactive", "☢️"),
        symbol("biohazard", "☣️"),
        symbol("arrow_up", "⬆️"),
        symbol("arrow_upper_right", "↗️"),
        symbol("arrow_right", "➡️"),
        symbol("arrow_lower_right", "↘️"),
        symbol("arrow_down", "⬇️"),
        symbol("arrow_lower_left", "↙️"),
        symbol("arrow_left", "⬅️"),
        symbol("arrow_upper_left", "↖️"),
        symbol("arrow_up_down", "↕️"),
        symbol("left_right_arrow", "↔️"),
        symbol("leftwards_arrow_with_hook", "↩️"),
        symbol("arrow_right_hook", "↪️"),
        symbol("arrow_heading_up", "⤴️"),
        symbol("arrow_heading_down", "⤵️"),
        symbol("arrows_clockwise", "🔃"),
        symbol("arrows_counterclockwise", "🔄"),
        symbol("back", "🔙"),
        symbol("end", "🔚"),
        symbol("on", "🔛"),
        symbol("soon", "🔜"),
        symbol("top", "🔝"),
        symbol("place_of_worship", "🛐"),
        symbol("atom_symbol", "⚛️"),
        symbol("om", "🕉️"),
        symbol("star_of_david", "✡️"),
        symbol("wheel_of_dharma", "☸️"),
        symbol("yin_yang", "☯️"),
        symbol("latin_cross", "✝️"),
        symbol("orthodox_cross", "☦️"),
        symbol("star_and_crescent", "☪️"),
        symbol("peace_symbol", "☮️"),
        symbol("menorah", "🕎"),
        symbol("six_pointed_star", "🔯"),
        symbol("khanda", "🪯"),
        symbol("aries", "♈"),
        symbol("taurus", "♉"),
        symbol("gemini", "♊"),
        symbol("cancer", "♋"),
        symbol("leo", "♌"),
        symbol("virgo", "♍"),
        symbol("libra", "♎"),
        symbol("scorpius", "♏"),
        symbol("sagittarius", "♐"),
        symbol("capricorn", "♑"),
        symbol("aquarius", "♒"),
        symbol("pisces", "♓"),
        symbol("ophiuchus", "⛎"),
        symbol("twisted_rightwards_arrows", "🔀"),
        symbol("repeat", "🔁"),
        symbol("repeat_one", "🔂"),
        symbol("arrow_forward", "▶️"),
        symbol("fast_forward", "⏩"),
        symbol("next_track_button", "⏭️"),
        symbol("play_or_pause_button", "⏯️"),
        symbol("arrow_backward", "◀️"),
        symbol("rewind", "⏪"),
        symbol("previous_track_button", "⏮️"),
        symbol("arrow_up_small", "🔼"),
        symbol("arrow_double_up", "⏫"),
        symbol("arrow_down_small", "🔽"),
        symbol("arrow_double_down", "⏬"),
        symbol("pause_button", "⏸️"),
        symbol("stop_button", "⏹️"),
        symbol("record_button", "⏺️"),
        symbol("eject_button", "⏏️"),
        symbol("cinema", "🎦"),
        symbol("low_brightness", "🔅"),
        symbol("high_brightness", "🔆"),
        symbol("signal_strength", "📶"),
        symbol("wireless", "🛜"),
        symbol("vibration_mode", "📳"),
        symbol("mobile_phone_off", "📴"),
        symbol("female_sign", "♀️"),
        symbol("male_sign", "♂️"),
        symbol("transgender_symbol", "⚧️"),
        symbol("heavy_multiplication_x", "✖️"),
        symbol("heavy_plus_sign", "➕"),
        symbol("heavy_minus_sign", "➖"),
        symbol("heavy_division_sign", "➗"),
        symbol("heavy_equals_sign", "🟰"),
        symbol("infinity", "♾️"),
        symbol("bangbang", "‼️"),
        symbol("interrobang", "⁉️"),
        symbol("question", "❓"),
        symbol("grey_question", "❔"),
        symbol("grey_exclamation", "❕"),
        symbol("exclamation", "❗", "heavy_exclamation_mark"),
        symbol("wavy_dash", "〰️"),
        symbol("currency_exchange", "💱"),
        symbol("heavy_dollar_sign", "💲"),
        symbol("medical_symbol", "⚕️"),
        symbol("recycle", "♻️"),
        symbol("fleur_de_lis", "⚜️"),
        symbol("trident", "🔱"),
        symbol("name_badge", "📛"),
        symbol("beginner", "🔰"),
        symbol("o", "⭕"),
        symbol("check_mark", "✅", "white_check_mark"),
        symbol("ballot_box_with_check", "☑️"),
        symbol("heavy_check_mark", "✔️"),
        symbol("x", "❌"),
        symbol("negative_squared_cross_mark", "❎"),
        symbol("curly_loop", "➰"),
        symbol("loop", "➿"),
        symbol("part_alternation_mark", "〽️"),
        symbol("eight_spoked_asterisk", "✳️"),
        symbol("eight_pointed_black_star", "✴️"),
        symbol("sparkle", "❇️"),
        symbol("copyright", "©️"),
        symbol("registered", "®️"),
        symbol("tm", "™️"),
        symbol("hash", "#️⃣"),
        symbol("asterisk", "*️⃣"),
        symbol("zero", "0️⃣"),
        symbol("one", "1️⃣"),
        symbol("two", "2️⃣"),
        symbol("three", "3️⃣"),
        symbol("four", "4️⃣"),
        symbol("five", "5️⃣"),
        symbol("six", "6️⃣"),
        symbol("seven", "7️⃣"),
        symbol("eight", "8️⃣"),
        symbol("nine", "9️⃣"),
        symbol("keycap_ten", "🔟"),
        symbol("capital_abcd", "🔠"),
        symbol("abcd", "🔡"),
        symbol("1234", "🔢"),
        symbol("symbols", "🔣"),
        symbol("abc", "🔤"),
        symbol("a", "🅰️"),
        symbol("ab", "🆎"),
        symbol("b", "🅱️"),
        symbol("cl", "🆑"),
        symbol("cool", "🆒"),
        symbol("free", "🆓"),
        symbol("information_source", "ℹ️"),
        symbol("id", "🆔"),
        symbol("m", "Ⓜ️"),
        symbol("new", "🆕"),
        symbol("ng", "🆖"),
        symbol("o2", "🅾️"),
        symbol("ok", "🆗"),
        symbol("parking", "🅿️"),
        symbol("sos", "🆘"),
        symbol("up", "🆙"),
        symbol("vs", "🆚"),
        symbol("koko", "🈁"),
        symbol("sa", "🈂️"),
        symbol("u6708", "🈷️"),
        symbol("u6709", "🈶"),
        symbol("u6307", "🈯"),
        symbol("ideograph_advantage", "🉐"),
        symbol("u5272", "🈹"),
        symbol("u7121", "🈚"),
        symbol("u7981", "🈲"),
        symbol("accept", "🉑"),
        symbol("u7533", "🈸"),
        symbol("u5408", "🈴"),
        symbol("u7a7a", "🈳"),
        symbol("congratulations", "㊗️"),
        symbol("secret", "㊙️"),
        symbol("u55b6", "🈺"),
        symbol("u6e80", "🈵"),
        symbol("red_circle", "🔴"),
        symbol("orange_circle", "🟠"),
        symbol("yellow_circle", "🟡"),
        symbol("green_circle", "🟢"),
        symbol("large_blue_circle", "🔵"),
        symbol("purple_circle", "🟣"),
        symbol("brown_circle", "🟤"),
        symbol("black_circle", "⚫"),
        symbol("white_circle", "⚪"),
        symbol("red_square", "🟥"),
        symbol("orange_square", "🟧"),
        symbol("yellow_square", "🟨"),
        symbol("green_square", "🟩"),
        symbol("blue_square", "🟦"),
        symbol("purple_square", "🟪"),
        symbol("brown_square", "🟫"),
        symbol("black_large_square", "⬛"),
        symbol("white_large_square", "⬜"),
        symbol("black_medium_square", "◼️"),
        symbol("white_medium_square", "◻️"),
        symbol("black_medium_small_square", "◾"),
        symbol("white_medium_small_square", "◽"),
        symbol("black_small_square", "▪️"),
        symbol("white_small_square", "▫️"),
        symbol("large_orange_diamond", "🔶"),
        symbol("large_blue_diamond", "🔷"),
        symbol("small_orange_diamond", "🔸"),
        symbol("small_blue_diamond", "🔹"),
        symbol("small_red_triangle", "🔺"),
        symbol("small_red_triangle_down", "🔻"),
        symbol("diamond_shape_with_a_dot_inside", "💠"),
        symbol("radio_button", "🔘"),
        symbol("white_square_button", "🔳"),
        symbol("black_square_button", "🔲"),
    )

    private val flags: List<EmojiPickerItem> = listOf(
        flag("checkered_flag", "🏁"),
        flag("triangular_flag_on_post", "🚩"),
        flag("crossed_flags", "🎌"),
        flag("black_flag", "🏴"),
        flag("white_flag", "🏳️"),
        flag("rainbow_flag", "🏳️‍🌈"),
        flag("transgender_flag", "🏳️‍⚧️"),
        flag("pirate_flag", "🏴‍☠️"),
        flag("ascension_island", "🇦🇨"),
        flag("andorra", "🇦🇩"),
        flag("united_arab_emirates", "🇦🇪"),
        flag("afghanistan", "🇦🇫"),
        flag("antigua_barbuda", "🇦🇬"),
        flag("anguilla", "🇦🇮"),
        flag("albania", "🇦🇱"),
        flag("armenia", "🇦🇲"),
        flag("angola", "🇦🇴"),
        flag("antarctica", "🇦🇶"),
        flag("argentina", "🇦🇷"),
        flag("american_samoa", "🇦🇸"),
        flag("austria", "🇦🇹"),
        flag("australia", "🇦🇺"),
        flag("aruba", "🇦🇼"),
        flag("aland_islands", "🇦🇽"),
        flag("azerbaijan", "🇦🇿"),
        flag("bosnia_herzegovina", "🇧🇦"),
        flag("barbados", "🇧🇧"),
        flag("bangladesh", "🇧🇩"),
        flag("belgium", "🇧🇪"),
        flag("burkina_faso", "🇧🇫"),
        flag("bulgaria", "🇧🇬"),
        flag("bahrain", "🇧🇭"),
        flag("burundi", "🇧🇮"),
        flag("benin", "🇧🇯"),
        flag("st_barthelemy", "🇧🇱"),
        flag("bermuda", "🇧🇲"),
        flag("brunei", "🇧🇳"),
        flag("bolivia", "🇧🇴"),
        flag("caribbean_netherlands", "🇧🇶"),
        flag("brazil", "🇧🇷"),
        flag("bahamas", "🇧🇸"),
        flag("bhutan", "🇧🇹"),
        flag("bouvet_island", "🇧🇻"),
        flag("botswana", "🇧🇼"),
        flag("belarus", "🇧🇾"),
        flag("belize", "🇧🇿"),
        flag("canada", "🇨🇦"),
        flag("cocos_islands", "🇨🇨"),
        flag("congo_kinshasa", "🇨🇩"),
        flag("central_african_republic", "🇨🇫"),
        flag("congo_brazzaville", "🇨🇬"),
        flag("switzerland", "🇨🇭"),
        flag("cote_divoire", "🇨🇮"),
        flag("cook_islands", "🇨🇰"),
        flag("chile", "🇨🇱"),
        flag("cameroon", "🇨🇲"),
        flag("cn", "🇨🇳"),
        flag("colombia", "🇨🇴"),
        flag("clipperton_island", "🇨🇵"),
        flag("costa_rica", "🇨🇷"),
        flag("cuba", "🇨🇺"),
        flag("cape_verde", "🇨🇻"),
        flag("curacao", "🇨🇼"),
        flag("christmas_island", "🇨🇽"),
        flag("cyprus", "🇨🇾"),
        flag("czech_republic", "🇨🇿"),
        flag("de", "🇩🇪"),
        flag("diego_garcia", "🇩🇬"),
        flag("djibouti", "🇩🇯"),
        flag("denmark", "🇩🇰"),
        flag("dominica", "🇩🇲"),
        flag("dominican_republic", "🇩🇴"),
        flag("algeria", "🇩🇿"),
        flag("ceuta_melilla", "🇪🇦"),
        flag("ecuador", "🇪🇨"),
        flag("estonia", "🇪🇪"),
        flag("egypt", "🇪🇬"),
        flag("western_sahara", "🇪🇭"),
        flag("eritrea", "🇪🇷"),
        flag("es", "🇪🇸"),
        flag("ethiopia", "🇪🇹"),
        flag("eu", "🇪🇺", "european_union"),
        flag("finland", "🇫🇮"),
        flag("fiji", "🇫🇯"),
        flag("falkland_islands", "🇫🇰"),
        flag("micronesia", "🇫🇲"),
        flag("faroe_islands", "🇫🇴"),
        flag("fr", "🇫🇷"),
        flag("gabon", "🇬🇦"),
        flag("gb", "🇬🇧", "uk"),
        flag("grenada", "🇬🇩"),
        flag("georgia", "🇬🇪"),
        flag("french_guiana", "🇬🇫"),
        flag("guernsey", "🇬🇬"),
        flag("ghana", "🇬🇭"),
        flag("gibraltar", "🇬🇮"),
        flag("greenland", "🇬🇱"),
        flag("gambia", "🇬🇲"),
        flag("guinea", "🇬🇳"),
        flag("guadeloupe", "🇬🇵"),
        flag("equatorial_guinea", "🇬🇶"),
        flag("greece", "🇬🇷"),
        flag("south_georgia_south_sandwich_islands", "🇬🇸"),
        flag("guatemala", "🇬🇹"),
        flag("guam", "🇬🇺"),
        flag("guinea_bissau", "🇬🇼"),
        flag("guyana", "🇬🇾"),
        flag("hong_kong", "🇭🇰"),
        flag("heard_mcdonald_islands", "🇭🇲"),
        flag("honduras", "🇭🇳"),
        flag("croatia", "🇭🇷"),
        flag("haiti", "🇭🇹"),
        flag("hungary", "🇭🇺"),
        flag("canary_islands", "🇮🇨"),
        flag("indonesia", "🇮🇩"),
        flag("ireland", "🇮🇪"),
        flag("israel", "🇮🇱"),
        flag("isle_of_man", "🇮🇲"),
        flag("india", "🇮🇳"),
        flag("british_indian_ocean_territory", "🇮🇴"),
        flag("iraq", "🇮🇶"),
        flag("iran", "🇮🇷"),
        flag("iceland", "🇮🇸"),
        flag("it", "🇮🇹"),
        flag("jersey", "🇯🇪"),
        flag("jamaica", "🇯🇲"),
        flag("jordan", "🇯🇴"),
        flag("jp", "🇯🇵"),
        flag("kenya", "🇰🇪"),
        flag("kyrgyzstan", "🇰🇬"),
        flag("cambodia", "🇰🇭"),
        flag("kiribati", "🇰🇮"),
        flag("comoros", "🇰🇲"),
        flag("st_kitts_nevis", "🇰🇳"),
        flag("north_korea", "🇰🇵"),
        flag("kr", "🇰🇷"),
        flag("kuwait", "🇰🇼"),
        flag("cayman_islands", "🇰🇾"),
        flag("kazakhstan", "🇰🇿"),
        flag("laos", "🇱🇦"),
        flag("lebanon", "🇱🇧"),
        flag("st_lucia", "🇱🇨"),
        flag("liechtenstein", "🇱🇮"),
        flag("sri_lanka", "🇱🇰"),
        flag("liberia", "🇱🇷"),
        flag("lesotho", "🇱🇸"),
        flag("lithuania", "🇱🇹"),
        flag("luxembourg", "🇱🇺"),
        flag("latvia", "🇱🇻"),
        flag("libya", "🇱🇾"),
        flag("morocco", "🇲🇦"),
        flag("monaco", "🇲🇨"),
        flag("moldova", "🇲🇩"),
        flag("montenegro", "🇲🇪"),
        flag("st_martin", "🇲🇫"),
        flag("madagascar", "🇲🇬"),
        flag("marshall_islands", "🇲🇭"),
        flag("macedonia", "🇲🇰"),
        flag("mali", "🇲🇱"),
        flag("myanmar", "🇲🇲"),
        flag("mongolia", "🇲🇳"),
        flag("macau", "🇲🇴"),
        flag("northern_mariana_islands", "🇲🇵"),
        flag("martinique", "🇲🇶"),
        flag("mauritania", "🇲🇷"),
        flag("montserrat", "🇲🇸"),
        flag("malta", "🇲🇹"),
        flag("mauritius", "🇲🇺"),
        flag("maldives", "🇲🇻"),
        flag("malawi", "🇲🇼"),
        flag("mexico", "🇲🇽"),
        flag("malaysia", "🇲🇾"),
        flag("mozambique", "🇲🇿"),
        flag("namibia", "🇳🇦"),
        flag("new_caledonia", "🇳🇨"),
        flag("niger", "🇳🇪"),
        flag("norfolk_island", "🇳🇫"),
        flag("nigeria", "🇳🇬"),
        flag("nicaragua", "🇳🇮"),
        flag("netherlands", "🇳🇱"),
        flag("norway", "🇳🇴"),
        flag("nepal", "🇳🇵"),
        flag("nauru", "🇳🇷"),
        flag("niue", "🇳🇺"),
        flag("new_zealand", "🇳🇿"),
        flag("oman", "🇴🇲"),
        flag("panama", "🇵🇦"),
        flag("peru", "🇵🇪"),
        flag("french_polynesia", "🇵🇫"),
        flag("papua_new_guinea", "🇵🇬"),
        flag("philippines", "🇵🇭"),
        flag("pakistan", "🇵🇰"),
        flag("poland", "🇵🇱"),
        flag("st_pierre_miquelon", "🇵🇲"),
        flag("pitcairn_islands", "🇵🇳"),
        flag("puerto_rico", "🇵🇷"),
        flag("palestinian_territories", "🇵🇸"),
        flag("portugal", "🇵🇹"),
        flag("palau", "🇵🇼"),
        flag("paraguay", "🇵🇾"),
        flag("qatar", "🇶🇦"),
        flag("reunion", "🇷🇪"),
        flag("romania", "🇷🇴"),
        flag("serbia", "🇷🇸"),
        flag("ru", "🇷🇺"),
        flag("rwanda", "🇷🇼"),
        flag("saudi_arabia", "🇸🇦"),
        flag("solomon_islands", "🇸🇧"),
        flag("seychelles", "🇸🇨"),
        flag("sudan", "🇸🇩"),
        flag("sweden", "🇸🇪"),
        flag("singapore", "🇸🇬"),
        flag("st_helena", "🇸🇭"),
        flag("slovenia", "🇸🇮"),
        flag("svalbard_jan_mayen", "🇸🇯"),
        flag("slovakia", "🇸🇰"),
        flag("sierra_leone", "🇸🇱"),
        flag("san_marino", "🇸🇲"),
        flag("senegal", "🇸🇳"),
        flag("somalia", "🇸🇴"),
        flag("suriname", "🇸🇷"),
        flag("south_sudan", "🇸🇸"),
        flag("sao_tome_principe", "🇸🇹"),
        flag("el_salvador", "🇸🇻"),
        flag("sint_maarten", "🇸🇽"),
        flag("syria", "🇸🇾"),
        flag("swaziland", "🇸🇿"),
        flag("tristan_da_cunha", "🇹🇦"),
        flag("turks_caicos_islands", "🇹🇨"),
        flag("chad", "🇹🇩"),
        flag("french_southern_territories", "🇹🇫"),
        flag("togo", "🇹🇬"),
        flag("thailand", "🇹🇭"),
        flag("tajikistan", "🇹🇯"),
        flag("tokelau", "🇹🇰"),
        flag("timor_leste", "🇹🇱"),
        flag("turkmenistan", "🇹🇲"),
        flag("tunisia", "🇹🇳"),
        flag("tonga", "🇹🇴"),
        flag("tr", "🇹🇷"),
        flag("trinidad_tobago", "🇹🇹"),
        flag("tuvalu", "🇹🇻"),
        flag("taiwan", "🇹🇼"),
        flag("tanzania", "🇹🇿"),
        flag("ukraine", "🇺🇦"),
        flag("uganda", "🇺🇬"),
        flag("us_outlying_islands", "🇺🇲"),
        flag("united_nations", "🇺🇳"),
        flag("us", "🇺🇸"),
        flag("uruguay", "🇺🇾"),
        flag("uzbekistan", "🇺🇿"),
        flag("vatican_city", "🇻🇦"),
        flag("st_vincent_grenadines", "🇻🇨"),
        flag("venezuela", "🇻🇪"),
        flag("british_virgin_islands", "🇻🇬"),
        flag("us_virgin_islands", "🇻🇮"),
        flag("vietnam", "🇻🇳"),
        flag("vanuatu", "🇻🇺"),
        flag("wallis_futuna", "🇼🇫"),
        flag("samoa", "🇼🇸"),
        flag("kosovo", "🇽🇰"),
        flag("yemen", "🇾🇪"),
        flag("mayotte", "🇾🇹"),
        flag("south_africa", "🇿🇦"),
        flag("zambia", "🇿🇲"),
        flag("zimbabwe", "🇿🇼"),
        flag("england", "🏴󠁧󠁢󠁥󠁮󠁧󠁿"),
        flag("scotland", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"),
        flag("wales", "🏴󠁧󠁢󠁷󠁬󠁳󠁿"),
    )

    private val ALIAS_PATTERN = Regex(
        """(?<![\p{L}\p{M}\p{N}_+\-]):[A-Za-z0-9_+\-]+:(?![\p{L}\p{M}\p{N}_+\-])""",
    )
    private val URL_PATTERN = Regex(
        """(?i)(?:\b(?:https?|ftp)://[^\s]+|\b(?:www\.)?[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.[a-z]{2,}(?::\d+)?(?:[/?#][^\s]*)?|\blocalhost(?::\d+)?(?:[/?#][^\s]*)?|\b(?:\d{1,3}\.){3}\d{1,3}(?::\d+)?(?:[/?#][^\s]*)?)""",
    )

    private fun rawAliasMatches(value: String) = ALIAS_PATTERN.findAll(value)

    private fun isAliasNameChar(value: Char): Boolean = value in 'a'..'z' ||
            value in 'A'..'Z' ||
            value in '0'..'9' ||
            value == '_' || value == '+' || value == '-'

    private fun isAliasBoundaryChar(value: Char): Boolean = value.isLetterOrDigit() ||
            when (Character.getType(value.code)) {
                Character.NON_SPACING_MARK.toInt(),
                Character.COMBINING_SPACING_MARK.toInt(),
                Character.ENCLOSING_MARK.toInt() -> true
                else -> false
            } || value == '_' || value == '+' || value == '-'

    private fun isEscaped(value: String, start: Int): Boolean = start > 0 && value[start - 1] == '\\'

    private fun isInsideUrl(value: String, start: Int, end: Int): Boolean = URL_PATTERN.findAll(value).any {
        it.range.first <= start && it.range.last + 1 >= end
    }
}
